# Generated by Django 6.0.1 on 2026-01-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_watcher_app", "0001_add_watch_city_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchcity",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
