# Generated by Django 6.0.1 on 2026-01-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_watcher_app", "0002_alter_watchcity_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchcity",
            name="lat",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="watchcity",
            name="lon",
            field=models.FloatField(default=0.0),
        ),
    ]
